name: API Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Newman and HTML Reporter
        run: npm install -g newman newman-reporter-htmlextra # اینجا هر دو reporter نصب می‌شوند

      - name: Run API Tests and generate reports
        # حالا Newman را اجرا می‌کنیم تا هم JUnit XML و هم HTML بسازد
        run: |
          newman run MyApiTests.postman_collection.json \
            --reporters junit,htmlextra \
            --reporter-junit-export results.xml \
            --reporter-htmlextra-export report.html

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports # اسم artifact را کمی تغییر می‌دهیم تا مشخص باشد شامل چند گزارش است
          path: | # .اینجا هر دو فایل گزارش را مشخص می‌کنیم
            results.xml
            report.html
